spring.application.name=backend
springdoc.swagger-ui.custom-path=/custom.css
spring.datasource.url=jdbc:mysql://localhost:3306/Lumina
spring.datasource.username=EXAMPLE
spring.datasource.password=EXAMPLE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver